// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateSnapshot(arg1:string,arg2:string):Promise<main.ResultDTO>;

export function DeleteSnapshot(arg1:string):Promise<main.ResultDTO>;

export function GetAggregatedCost():Promise<number>;

export function GetConnectedAgents():Promise<Array<string>>;

export function GetCostByAgent(arg1:string):Promise<number>;

export function GetCostByHours(arg1:number):Promise<number>;

export function GetFileChanges(arg1:string,arg2:string):Promise<Array<main.FileChangeDTO>>;

export function GetSessions():Promise<Array<main.SessionDTO>>;

export function KillSession(arg1:string,arg2:string):Promise<main.ResultDTO>;

export function ListSnapshots():Promise<Array<main.SnapshotDTO>>;

export function Rollback(arg1:string,arg2:string):Promise<main.ResultDTO>;
